apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hetzner-driver
spec:
  template:
    metadata:
      labels:
        app: hetzner-driver
    spec:
      containers:
        - image: stevenklar/hetzner-volume-driver:0.1
          name: hetzner-driver
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /kubelet-plugins
              name: kubelet-plugins
      volumes:
        - hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
          name: kubelet-plugins
