apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hetzner-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hetzner-provisioner-role
subjects:
  - kind: ServiceAccount
    name: hetzner-provisioner
    namespace: default
