apiVersion: apps/v1
kind: Deployment
metadata:
  name: hetzner-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hetzner-provisioner
  template:
    metadata:
      labels:
        app: hetzner-provisioner
    spec:
      containers:
        - name: provisioner
          image: stevenklar/hetzner-storage-provisioner:latest
          env:
            - name: HETZNER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hetzner-cloud
