apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hetzner-cloud-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: hetzner-cloud-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
