#!/bin/sh

set -o errexit
set -o pipefail

if [ ! -d /kubelet-plugins/stevenklar~hetzner-cloud-driver ]; then
  mkdir /kubelet-plugins/stevenklar~hetzner-cloud-driver
fi

cp /usr/local/bin/driver /kubelet-plugins/stevenklar~hetzner-cloud-driver/.tmp_driver
mv -f /kubelet-plugins/stevenklar~hetzner-cloud-driver/.tmp_driver /kubelet-plugins/stevenklar~hetzner-cloud-driver/hetzner-cloud-driver

while : ; do
  sleep 3600
done
