#!/bin/sh

set -o errexit
set -o pipefail

if [ ! -d /kubelet-plugins/hetzner-cloud-storage ]; then
  mkdir /kubelet-plugins/hetzner-cloud-storage
fi

cp /usr/local/bin/driver /kubelet-plugins/hetzner-cloud-storage/.tmp_driver
mv -f /kubelet-plugins/hetzner-cloud-storage/.tmp_driver /kubelet-plugins/hetzner-cloud-storage/driver

while : ; do
  sleep 3600
done
